### ISSUE TITLE
mkvirtualenv slither make: mkvirtualenv: Command not found make: *** [Makefile:2: install] Error 127 trying to run make install

### ISSUE THREAD

**Issue by EricFROL** [kkamalov/snake-den#2]
As the title says, when I try to run make install, it returns me that error (mkvirtualenv slither make: mkvirtualenv: Command not found make: *** [Makefile:2: install] Error 127). So; What should i do now?

TY in advance ;D

PD: Hope there is anyone still here

**Comment by joshblum** [comment]
@EricFROL you need `virtualenvwrapper` installed. https://www.geeksforgeeks.org/using-mkvirtualenv-to-create-new-virtual-environment-python/
